### ISSUE TITLE
typeof rig doesn't satisfy instanceTree

### ISSUE THREAD

**Issue by Ukendio** [Validark/Roblox-TS-Libraries#11]
type doesn't satisfy the InstanceTree of the module "validate-tree"
`
export declare type CharacterRigR6 = EvaluateInstanceTree<typeof CharacterRigR6>;
export declare type CharacterRigR15 = EvaluateInstanceTree<typeof CharacterRigR15>;
`

**Comment by Validark** [comment]
Fixed by https://github.com/Validark/Roblox-TS-Libraries/commit/920736825c6f66a13f00e6ce8f6f43820a890d56! Try updating to the latest version!
