### ISSUE TITLE
Add license attribution

### ISSUE THREAD

**Issue by LPGhatguy** [Validark/Roblox-TS-Libraries#17]
Some of these projects appear to be derivative works or redistributions of other projects. In particular, [the spring library contained here](https://github.com/Validark/Roblox-TS-Libraries/blob/master/spring/init.lua) appears to be a transcription of [Fraktality's spr library](https://github.com/Fraktality/spr/blob/master/spr.lua).

Listing a username here is not generally enough to satisfy the MIT license. It's generally required to include [the original license](https://github.com/Fraktality/spr/blob/master/LICENSE).

I recommend reviewing the other modules in the repo and their attribution. License violations are no good, and respecting each other's work is what makes open source hum!

**Comment by Validark** [comment]
My apologies, I didn't consider this. Fixed with https://github.com/Validark/Roblox-TS-Libraries/commit/0f2ff763f81ddd6634f6c9934c86845e172f4a91
