### ISSUE TITLE
validate-tree: passing 'game' as object throws SecurityContext error.

### ISSUE THREAD

**Issue by ddavness** [Validark/Roblox-TS-Libraries#2]
If the "root" of the tree is `game`, `validateTree` will hit a point where it tries to index services it doesn't have access to (due to SecurityContext restrictions) - and therefore, error.

Take the example:

```ts
const tree = {
    $className: "DataModel",
    Workspace: "Workspace",
    ReplicatedStorage: {
        $className: "ReplicatedStorage",
        sysNetwork: {
            $className: "Folder",
            getSelfShip: "RemoteFunction",
        },
    },
    ServerStorage: {
        $className: "ServerStorage",
        vehicles: "Folder",
    },
} as const;

if (!validateTree(game, tree)) {
    throw "Tree validation failed! Are you sure you did not forget anything?";
}
```

it will error with

> The current identity (2) cannot Class security check (lacking permission 6)

*(Note: I **think** this actually used to work, but a Roblox update may have inadvertently broken it)*

**Comment by Validark** [comment]
I think this ought to be fixed by calls to GetService, instead of sticking things in pcall.

**Comment by ddavness** [comment]
redone the PR, as an implementation proposal (you can always use one of your own, if you want to)
