### ISSUE TITLE
Typing the tree constant as InstanceTree results in any child Instance being never

### ISSUE THREAD

**Issue by suchasaltylemon** [Validark/Roblox-TS-Libraries#24]
Using the `InstanceTree` type to type the const tree parameter results in its children being `never`.

**Using InstanceTree type**
![image](https://user-images.githubusercontent.com/46686300/163716970-64cb11bb-4800-4f91-9814-43a78ab6c5c4.png)

**Using as const**
![image](https://user-images.githubusercontent.com/46686300/163717002-08f9652e-dccb-4e39-81ff-fc57b5d642f8.png)

This is not expected behaviour as the `tree` parameter expects type `InstanceTree`

**Comment by Validark** [comment]
TypeScript is structurally typed, so if you declare `computerTree` to be the `InstanceTree` type, you lose all inferred type information. You aren't merely adding a constraint, you are defining the type to be very non-specific. The `tree` parameter expects a type which extends `InstanceType`, and that's how `validateTree` is able to process your particular type into the right output. This is a fundamental property of the TypeScript type system. Your demonstration gives exactly what you should expect. For reference, this is the code that does the type conversion:

https://github.com/Validark/Roblox-TS-Libraries/blob/3d354e0f208ba38c1b3b1aee3fe8f380786ab054/validate-tree/src/index.ts#L44-L48

https://github.com/Validark/Roblox-TS-Libraries/blob/3d354e0f208ba38c1b3b1aee3fe8f380786ab054/validate-tree/src/index.ts#L18-L33

https://github.com/Validark/Roblox-TS-Libraries/blob/3d354e0f208ba38c1b3b1aee3fe8f380786ab054/validate-tree/src/index.ts#L1-L9

If you're interested in constraining your object literal type without losing specific type information, try using [the identity helper function](https://roblox-ts.com/docs/api/functions#identity).

**Comment by Validark** [comment]
Correction: What you want is a `constrain` function like so:

```ts
/** Returns the passed in value. The return type matches the type argument.
 * e.g. `identity<1 | 2 | 3>(3)` returns a value of type `1 | 2 | 3`
 */
function identity<T>(arg: T) {
    return arg;
}

/** Creates a new identity function with a type argument `T` which returns the passed in literal type which must be assignable to `T`.
 * e.g. `constrain<1 | 2 | 3>()(3)` returns a value of `3`
 */
function constrain<T>() {
    return identity as <Q extends T>(arg: Q) => Q;
}
```

I opened a proposal to make the `constrain` function built-in to the compiler so that you do not have to pay the cost of a function call at run-time. https://github.com/roblox-ts/roblox-ts/issues/2080
