### ISSUE TITLE
When Roblox is unable to load a player's appearance, yield-for-character yields infinitely

### ISSUE THREAD

**Issue by Xuleos** [Validark/Roblox-TS-Libraries#6]
![image](https://user-images.githubusercontent.com/37721396/85895800-56beb300-b7c5-11ea-8c95-1f58f7249f39.png)
![image](https://user-images.githubusercontent.com/37721396/85895816-5b836700-b7c5-11ea-9675-9bd6f30eab29.png)
mans is still functional and should probably be classified as loaded
![image](https://user-images.githubusercontent.com/37721396/85896056-caf95680-b7c5-11ea-93c0-debbbcd46ff7.png)

This might be completely out of your scope to fix as I'm assuming the only way to prevent this would be to no longer include all of the scale values under humanoid and BodyColors in the tree

**Comment by Validark** [comment]
Are there times when Roblox characters will continue to not load character appearance forever (at least, so far)? If so, I don't know that this library can really address that. That problem should be solved on Roblox's side, not mine. Is this a studio-only problem? Is there any way this can be prevented?

**Comment by Xuleos** [comment]
There are rare times when Roblox won't be able to load the player's appearance in-game, although I don't really see how you guys would be able to fix the infinite yielding without taking away the yield for scale objects and BodyColors
